# Generated by Django 5.2.8 on 2025-11-26 03:22

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tester_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proposal_id", models.CharField(max_length=255)),
                (
                    "audit_type",
                    models.CharField(
                        choices=[
                            ("Tahunan", "Tahunan"),
                            ("IPO", "IPO"),
                            ("Interim - Audit", "Interim - Audit"),
                            ("Interim - Review", "Interim - Review"),
                            ("Non-Audit Umum", "Non-Audit Umum"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "fiscal_year_end",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.DateField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("base_fee", models.PositiveIntegerField()),
                ("assistance_fee", models.PositiveIntegerField()),
                ("ope_fee", models.PositiveIntegerField()),
                ("sub_fee", models.PositiveIntegerField()),
                ("num_termins", models.PositiveIntegerField()),
                ("termin_values", models.JSONField()),
                ("total_percentage", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposal",
                        to="tester_app.client",
                    ),
                ),
            ],
        ),
    ]
