# Generated by Django 5.2.8 on 2025-11-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tester_app", "0002_proposal"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="total_fee",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
