# Generated by Django 5.2.8 on 2025-11-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tester_app", "0003_proposal_total_fee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proposal",
            name="sub_fee",
        ),
        migrations.AddField(
            model_name="proposal",
            name="termin_fee",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
