# Generated by Django 5.2.8 on 2025-11-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tester_app", "0004_remove_proposal_sub_fee_proposal_termin_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="total_fee",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
