# Generated by Django 5.2.8 on 2025-12-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tester_app", "0005_alter_proposal_total_fee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Temp",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temp_id", models.CharField(max_length=255)),
                (
                    "temp_select",
                    models.CharField(
                        choices=[
                            ("Choice 1", "Choice 1"),
                            ("Choice 2", "Choice 2"),
                            ("Choice 3", "Choice 3"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
